### ISSUE TITLE
Npgsql.NpgsqlException (0x80004005): Failed to connect to [::1]:5432

### ISSUE THREAD

**Issue by w7rus** [techiedesu/MusicPlayerBackend#5]
Backend tries connecting to db on 5432 port, while Infr compose host port for Postgres is 9732

**Comment by w7rus** [comment]
Change to ```User ID=postgres;Password=postgres;Host=host.docker.internal;Port=9732;Database=MusicPlayerBackend;``` solves the problem

**Comment by techiedesu** [comment]
Не знал что резко так начнёшь работать. Допушил ченжи.
